CREATE SCHEMA "product";
--> statement-breakpoint
CREATE SCHEMA "user";
--> statement-breakpoint
CREATE TYPE "product"."option_type" AS ENUM('RATE', 'ABSOLUTE');--> statement-breakpoint
CREATE TYPE "user"."auth_role" AS ENUM('USER', 'ADMIN', 'LEFT');--> statement-breakpoint
CREATE TYPE "user"."auth_type" AS ENUM('NATIVE', 'SOCIAL', 'CROSS');--> statement-breakpoint
CREATE TABLE "user"."address" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "user"."address_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" bigint NOT NULL,
	"postal_code" varchar(7) NOT NULL,
	"default_address" text NOT NULL,
	"detail_address" text,
	"extra_address" text,
	"is_main" boolean DEFAULT false NOT NULL,
	"is_valid" boolean DEFAULT true NOT NULL,
	"created_at" timestamp (6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp (6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"deleted_at" timestamp (6) with time zone,
	CONSTRAINT "pk_address" PRIMARY KEY("id"),
	CONSTRAINT "ck_address_deleted_state" CHECK ((
          ("user"."address"."is_valid" = TRUE AND "user"."address"."deleted_at" IS NULL)
          OR
          ("user"."address"."is_valid" = FALSE AND "user"."address"."deleted_at" IS NOT NULL)
          ))
);
--> statement-breakpoint
CREATE TABLE "major_category" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "major_category_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"sort_key" bigint NOT NULL,
	"major_category_name" varchar(255) NOT NULL,
	"is_valid" boolean NOT NULL,
	"created_at" timestamp (6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp (6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"deleted_at" timestamp (6) with time zone,
	CONSTRAINT "pk_major_category" PRIMARY KEY("id"),
	CONSTRAINT "uq_major_category_sort_key" UNIQUE("sort_key"),
	CONSTRAINT "ck_major_category_deleted_state" CHECK ((
          ("major_category"."is_valid" = TRUE AND "major_category"."deleted_at" IS NULL)
          OR
          ("major_category"."is_valid" = FALSE AND "major_category"."deleted_at" IS NOT NULL)
          ))
);
--> statement-breakpoint
CREATE TABLE "miner_category" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "miner_category_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"major_category_id" bigint NOT NULL,
	"sort_key" bigint NOT NULL,
	"miner_category_name" varchar(255) NOT NULL,
	"is_valid" boolean NOT NULL,
	"created_at" timestamp (6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp (6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"deleted_at" timestamp (6) with time zone,
	CONSTRAINT "pk_miner_category" PRIMARY KEY("id"),
	CONSTRAINT "uq_miner_category_sort_key" UNIQUE("major_category_id","sort_key"),
	CONSTRAINT "ck_miner_category_deleted_state" CHECK ((
          ("miner_category"."is_valid" = TRUE AND "miner_category"."deleted_at" IS NULL)
          OR
          ("miner_category"."is_valid" = FALSE AND "miner_category"."deleted_at" IS NOT NULL)
          ))
);
--> statement-breakpoint
CREATE TABLE "user"."native_user" (
	"id" bigint NOT NULL,
	"password_hash" varchar(255) NOT NULL,
	CONSTRAINT "pk_native_user" PRIMARY KEY("id")
);
--> statement-breakpoint
CREATE TABLE "user"."refresh_token" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "user"."refresh_token_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" bigint NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires_at" timestamp (6) with time zone NOT NULL,
	CONSTRAINT "pk_refresh_token" PRIMARY KEY("id"),
	CONSTRAINT "uq_active_refresh_token" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "user"."social_provider" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "user"."social_provider_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"provider_name" varchar(255) NOT NULL,
	CONSTRAINT "pk_social_provider" PRIMARY KEY("id"),
	CONSTRAINT "uq_social_provider_name" UNIQUE("provider_name")
);
--> statement-breakpoint
CREATE TABLE "user"."social_user" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "user"."social_user_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" bigint NOT NULL,
	"provider_id" bigint NOT NULL,
	"provider_user_name" varchar(255) NOT NULL,
	CONSTRAINT "pk_social_user" PRIMARY KEY("id"),
	CONSTRAINT "uq_social_user_provider" UNIQUE("user_id","provider_id","provider_user_name")
);
--> statement-breakpoint
CREATE TABLE "user"."user" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "user"."user_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_name" varchar(255) NOT NULL,
	"real_name" varchar(255),
	"phone_number" varchar(20),
	"email" varchar(255),
	"auth_type" "user"."auth_type" DEFAULT 'NATIVE' NOT NULL,
	"auth_role" "user"."auth_role" DEFAULT 'USER' NOT NULL,
	"created_at" timestamp (6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp (6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"deleted_at" timestamp (6) with time zone,
	CONSTRAINT "pk_user" PRIMARY KEY("id"),
	CONSTRAINT "ck_user_deleted_state" CHECK ((
          ("user"."user"."auth_role" <> 'LEFT' AND "user"."user"."deleted_at" IS NULL)
          OR
          ("user"."user"."auth_role" = 'LEFT' AND "user"."user"."deleted_at" IS NOT NULL)
          ))
);
--> statement-breakpoint
CREATE TABLE "product"."detail_option" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "product"."detail_option_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"option_id" bigint NOT NULL,
	"option_detail_name" varchar(255) NOT NULL,
	"option_value" bigint NOT NULL,
	"is_valid" boolean DEFAULT true NOT NULL,
	"created_at" timestamp (6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp (6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"deleted_at" timestamp (6) with time zone,
	CONSTRAINT "pk_detail_option" PRIMARY KEY("id"),
	CONSTRAINT "ck_option_deleted_state" CHECK ((
          ("product"."detail_option"."is_valid" = TRUE AND "product"."detail_option"."deleted_at" IS NULL)
          OR
          ("product"."detail_option"."is_valid" = FALSE AND "product"."detail_option"."deleted_at" IS NOT NULL)
          ))
);
--> statement-breakpoint
CREATE TABLE "product"."option" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "product"."option_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"major_category_id" bigint NOT NULL,
	"sort_key" bigint NOT NULL,
	"option_name" varchar(255) NOT NULL,
	"is_valid" boolean DEFAULT true NOT NULL,
	"created_at" timestamp (6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp (6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"deleted_at" timestamp (6) with time zone,
	CONSTRAINT "pk_option" PRIMARY KEY("id"),
	CONSTRAINT "uq_option_sort_key" UNIQUE("major_category_id","sort_key"),
	CONSTRAINT "ck_option_deleted_state" CHECK ((
          ("product"."option"."is_valid" = TRUE AND "product"."option"."deleted_at" IS NULL)
          OR
          ("product"."option"."is_valid" = FALSE AND "product"."option"."deleted_at" IS NOT NULL)
          ))
);
--> statement-breakpoint
ALTER TABLE "user"."address" ADD CONSTRAINT "fk_address_user" FOREIGN KEY ("user_id") REFERENCES "user"."user"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "miner_category" ADD CONSTRAINT "fk_category" FOREIGN KEY ("major_category_id") REFERENCES "public"."major_category"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "user"."native_user" ADD CONSTRAINT "fk_native_user" FOREIGN KEY ("id") REFERENCES "user"."user"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "user"."refresh_token" ADD CONSTRAINT "fk_refresh_token_user" FOREIGN KEY ("user_id") REFERENCES "user"."user"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "user"."social_user" ADD CONSTRAINT "fk_social_user" FOREIGN KEY ("user_id") REFERENCES "user"."user"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "user"."social_user" ADD CONSTRAINT "fk_social_provider" FOREIGN KEY ("provider_id") REFERENCES "user"."social_provider"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "product"."detail_option" ADD CONSTRAINT "fk_detail_option" FOREIGN KEY ("option_id") REFERENCES "product"."option"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "product"."option" ADD CONSTRAINT "fk_option_category" FOREIGN KEY ("major_category_id") REFERENCES "public"."major_category"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
CREATE UNIQUE INDEX "uq_main_address" ON "user"."address" USING btree ("user_id") WHERE "user"."address"."is_main" = TRUE;--> statement-breakpoint
CREATE INDEX "ix_address_main" ON "user"."address" USING btree ("user_id","is_main" DESC NULLS LAST,"created_at") WHERE "user"."address"."is_valid" = TRUE;--> statement-breakpoint
CREATE UNIQUE INDEX "uq_active_major_category" ON "major_category" USING btree ("major_category_name") WHERE "major_category"."is_valid" = TRUE;--> statement-breakpoint
CREATE INDEX "ix_major_category_sort" ON "major_category" USING btree ("sort_key") WHERE "major_category"."is_valid" = TRUE;--> statement-breakpoint
CREATE UNIQUE INDEX "uq_active_miner_category" ON "miner_category" USING btree ("major_category_id","miner_category_name") WHERE "miner_category"."is_valid" = TRUE;--> statement-breakpoint
CREATE INDEX "ix_miner_category_sort" ON "miner_category" USING btree ("sort_key") WHERE "miner_category"."is_valid" = TRUE;--> statement-breakpoint
CREATE INDEX "ix_refresh_token_user" ON "user"."refresh_token" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "ix_refresh_token_expire" ON "user"."refresh_token" USING btree ("expires_at");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_user_name" ON "user"."user" USING btree ("user_name") WHERE "user"."user"."auth_type" <> 'SOCIAL' AND "user"."user"."auth_role" <> 'LEFT';--> statement-breakpoint
CREATE INDEX "ix_active_user_created_at" ON "user"."user" USING btree ("created_at" DESC NULLS LAST) WHERE "user"."user"."auth_role" <> 'LEFT';--> statement-breakpoint
CREATE INDEX "ix_delete_user_deleted_at" ON "user"."user" USING btree ("deleted_at" DESC NULLS LAST) WHERE "user"."user"."auth_role" = 'LEFT';--> statement-breakpoint
CREATE UNIQUE INDEX "uq_detail_option_value" ON "product"."detail_option" USING btree ("option_id","option_value" DESC NULLS LAST) WHERE "product"."detail_option"."is_valid" = TRUE;--> statement-breakpoint
CREATE UNIQUE INDEX "uq_active_detail_option" ON "product"."detail_option" USING btree ("option_id","option_detail_name") WHERE "product"."detail_option"."is_valid" = TRUE;--> statement-breakpoint
CREATE UNIQUE INDEX "uq_active_option" ON "product"."option" USING btree ("major_category_id","option_name") WHERE "product"."option"."is_valid" = TRUE;--> statement-breakpoint
CREATE INDEX "ix_option_sort" ON "product"."option" USING btree ("major_category_id","sort_key") WHERE "product"."option"."is_valid" = TRUE;