CREATE SCHEMA "order";
--> statement-breakpoint
CREATE SCHEMA "product";
--> statement-breakpoint
CREATE SCHEMA "user";
--> statement-breakpoint
CREATE TYPE "order"."delivery_status" AS ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'CANCELED');--> statement-breakpoint
CREATE TYPE "order"."payment_status" AS ENUM('PENDING', 'COMPLETED', 'CANCELED');--> statement-breakpoint
CREATE TYPE "product"."option_type" AS ENUM('RATE', 'ABSOLUTE');--> statement-breakpoint
CREATE TYPE "user"."auth_role" AS ENUM('USER', 'ADMIN', 'LEFT');--> statement-breakpoint
CREATE TYPE "user"."auth_type" AS ENUM('NATIVE', 'SOCIAL', 'CROSS');--> statement-breakpoint
CREATE TABLE "order"."cart" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "order"."cart_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"product_id" bigint NOT NULL,
	"user_id" bigint NOT NULL,
	"quantity" bigint NOT NULL,
	"created_at" timestamp (6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "pk_cart" PRIMARY KEY("id")
);
--> statement-breakpoint
CREATE TABLE "order"."cart_option" (
	"id" bigint NOT NULL,
	"cart_id" bigint NOT NULL,
	CONSTRAINT "pk_cart_option" PRIMARY KEY("id")
);
--> statement-breakpoint
CREATE TABLE "order"."delivery" (
	"id" bigint NOT NULL,
	"delivery_status" "order"."delivery_status" DEFAULT 'PENDING' NOT NULL,
	"postal_code" varchar(7) NOT NULL,
	"default_address" text NOT NULL,
	"detail_address" text,
	"extra_address" text,
	"courier_company" varchar,
	"invoice_number" varchar,
	"delivered_at" timestamp (6) with time zone,
	"arrived_at" timestamp (6) with time zone,
	"cancled_at" timestamp (6) with time zone,
	CONSTRAINT "pk_delivery" PRIMARY KEY("id"),
	CONSTRAINT "ck_delivery_state" CHECK ((
          ("order"."delivery"."delivery_status" <> 'CANCELED' AND "order"."delivery"."cancled_at" IS NULL)
          OR
          ("order"."delivery"."delivery_status" = 'CANCELED' AND "order"."delivery"."cancled_at" IS NOT NULL)
          ))
);
--> statement-breakpoint
CREATE TABLE "order"."order" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "order"."order_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"payment_id" bigint NOT NULL,
	"product_name" varchar(255) NOT NULL,
	"quantity" bigint NOT NULL,
	CONSTRAINT "pk_order" PRIMARY KEY("id")
);
--> statement-breakpoint
CREATE TABLE "order"."order_option" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "order"."order_option_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"order_id" bigint NOT NULL,
	"sort_key" bigint NOT NULL,
	"option_name" varchar(255) NOT NULL,
	"detail_option_name" varchar(255) NOT NULL,
	"option_value" bigint NOT NULL,
	CONSTRAINT "pk_order_option" PRIMARY KEY("id"),
	CONSTRAINT "uq_order_option_name" UNIQUE("order_id","option_name","detail_option_name")
);
--> statement-breakpoint
CREATE TABLE "order"."payment" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "order"."payment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"payment_method_id" bigint NOT NULL,
	"user_id" bigint NOT NULL,
	"product_price" bigint NOT NULL,
	"delivery_price" bigint NOT NULL,
	"payment_status" "order"."payment_status" DEFAULT 'PENDING' NOT NULL,
	"created_at" timestamp (6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp (6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"deleted_at" timestamp (6) with time zone,
	CONSTRAINT "pk_payment" PRIMARY KEY("id"),
	CONSTRAINT "ck_payment_state" CHECK ((
          ("order"."payment"."payment_status" <> 'CANCELED' AND "order"."payment"."deleted_at" IS NULL)
          OR
          ("order"."payment"."payment_status" = 'CANCELED' AND "order"."payment"."deleted_at" IS NOT NULL)
          ))
);
--> statement-breakpoint
CREATE TABLE "order"."payment_method" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "order"."payment_method_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"payment_method_name" varchar(255) NOT NULL,
	"is_valid" boolean DEFAULT true NOT NULL,
	"created_at" timestamp (6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp (6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"deleted_at" timestamp (6) with time zone,
	CONSTRAINT "pk_payment_method" PRIMARY KEY("id"),
	CONSTRAINT "uq_payment_method_name" UNIQUE("payment_method_name"),
	CONSTRAINT "ck_payment_method_state" CHECK ((
          ("order"."payment_method"."is_valid" = TRUE AND "order"."payment_method"."deleted_at" IS NULL)
          OR
          ("order"."payment_method"."is_valid" = FALSE AND "order"."payment_method"."deleted_at" IS NOT NULL)
          ))
);
--> statement-breakpoint
CREATE TABLE "product"."detail_option" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "product"."detail_option_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"option_id" bigint NOT NULL,
	"detail_option_name" varchar(255) NOT NULL,
	"option_value" bigint NOT NULL,
	"is_valid" boolean DEFAULT true NOT NULL,
	"created_at" timestamp (6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp (6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"deleted_at" timestamp (6) with time zone,
	CONSTRAINT "pk_detail_option" PRIMARY KEY("id"),
	CONSTRAINT "ck_option_deleted_state" CHECK ((
          ("product"."detail_option"."is_valid" = TRUE AND "product"."detail_option"."deleted_at" IS NULL)
          OR
          ("product"."detail_option"."is_valid" = FALSE AND "product"."detail_option"."deleted_at" IS NOT NULL)
          ))
);
--> statement-breakpoint
CREATE TABLE "product"."option" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "product"."option_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"major_category_id" bigint NOT NULL,
	"sort_key" bigint NOT NULL,
	"option_name" varchar(255) NOT NULL,
	"is_valid" boolean DEFAULT true NOT NULL,
	"created_at" timestamp (6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp (6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"deleted_at" timestamp (6) with time zone,
	CONSTRAINT "pk_option" PRIMARY KEY("id"),
	CONSTRAINT "uq_option_sort_key" UNIQUE("major_category_id","sort_key"),
	CONSTRAINT "ck_option_deleted_state" CHECK ((
          ("product"."option"."is_valid" = TRUE AND "product"."option"."deleted_at" IS NULL)
          OR
          ("product"."option"."is_valid" = FALSE AND "product"."option"."deleted_at" IS NOT NULL)
          ))
);
--> statement-breakpoint
CREATE TABLE "product"."product" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "product"."product_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"miner_category_id" bigint NOT NULL,
	"product_name" varchar(255) NOT NULL,
	"productComments" text NOT NULL,
	"price" bigint NOT NULL,
	"discounted_rate" bigint NOT NULL,
	"is_recommended" boolean DEFAULT false NOT NULL,
	"is_valid" boolean DEFAULT true NOT NULL,
	"created_at" timestamp (6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp (6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"deleted_at" timestamp (6) with time zone,
	CONSTRAINT "pk_product" PRIMARY KEY("id"),
	CONSTRAINT "ck_product_deleted_state" CHECK ((
          ("product"."product"."is_valid" = TRUE AND "product"."product"."deleted_at" IS NULL)
          OR
          ("product"."product"."is_valid" = FALSE AND "product"."product"."deleted_at" IS NOT NULL)
          ))
);
--> statement-breakpoint
CREATE TABLE "product"."product_image" (
	"id" bigint NOT NULL,
	"file_name" varchar(255) NOT NULL,
	"original_name" varchar(255) NOT NULL,
	"mime_type" varchar(255) NOT NULL,
	"file_size" bigint NOT NULL,
	"created_at" timestamp (6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "pk_product_image" PRIMARY KEY("id"),
	CONSTRAINT "uq_file_name" UNIQUE("file_name")
);
--> statement-breakpoint
CREATE TABLE "major_category" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "major_category_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"sort_key" bigint NOT NULL,
	"major_category_name" varchar(255) NOT NULL,
	"is_valid" boolean NOT NULL,
	"created_at" timestamp (6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp (6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"deleted_at" timestamp (6) with time zone,
	CONSTRAINT "pk_major_category" PRIMARY KEY("id"),
	CONSTRAINT "uq_major_category_sort_key" UNIQUE("sort_key"),
	CONSTRAINT "ck_major_category_deleted_state" CHECK ((
          ("major_category"."is_valid" = TRUE AND "major_category"."deleted_at" IS NULL)
          OR
          ("major_category"."is_valid" = FALSE AND "major_category"."deleted_at" IS NOT NULL)
          ))
);
--> statement-breakpoint
CREATE TABLE "miner_category" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "miner_category_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"major_category_id" bigint NOT NULL,
	"sort_key" bigint NOT NULL,
	"miner_category_name" varchar(255) NOT NULL,
	"is_valid" boolean NOT NULL,
	"created_at" timestamp (6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp (6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"deleted_at" timestamp (6) with time zone,
	CONSTRAINT "pk_miner_category" PRIMARY KEY("id"),
	CONSTRAINT "uq_miner_category_sort_key" UNIQUE("major_category_id","sort_key"),
	CONSTRAINT "ck_miner_category_deleted_state" CHECK ((
          ("miner_category"."is_valid" = TRUE AND "miner_category"."deleted_at" IS NULL)
          OR
          ("miner_category"."is_valid" = FALSE AND "miner_category"."deleted_at" IS NOT NULL)
          ))
);
--> statement-breakpoint
CREATE TABLE "user"."address" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "user"."address_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" bigint NOT NULL,
	"postal_code" varchar(7) NOT NULL,
	"default_address" text NOT NULL,
	"detail_address" text,
	"extra_address" text,
	"is_main" boolean DEFAULT false NOT NULL,
	"is_valid" boolean DEFAULT true NOT NULL,
	"created_at" timestamp (6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp (6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"deleted_at" timestamp (6) with time zone,
	CONSTRAINT "pk_address" PRIMARY KEY("id"),
	CONSTRAINT "ck_address_deleted_state" CHECK ((
          ("user"."address"."is_valid" = TRUE AND "user"."address"."deleted_at" IS NULL)
          OR
          ("user"."address"."is_valid" = FALSE AND "user"."address"."deleted_at" IS NOT NULL)
          ))
);
--> statement-breakpoint
CREATE TABLE "user"."native_user" (
	"id" bigint NOT NULL,
	"password_hash" varchar(255) NOT NULL,
	CONSTRAINT "pk_native_user" PRIMARY KEY("id")
);
--> statement-breakpoint
CREATE TABLE "user"."refresh_token" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "user"."refresh_token_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" bigint NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires_at" timestamp (6) with time zone NOT NULL,
	CONSTRAINT "pk_refresh_token" PRIMARY KEY("id"),
	CONSTRAINT "uq_active_refresh_token" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "user"."social_provider" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "user"."social_provider_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"provider_name" varchar(255) NOT NULL,
	"is_valid" boolean DEFAULT true NOT NULL,
	"created_at" timestamp (6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp (6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"deleted_at" timestamp (6) with time zone,
	CONSTRAINT "pk_social_provider" PRIMARY KEY("id"),
	CONSTRAINT "uq_social_provider_name" UNIQUE("provider_name"),
	CONSTRAINT "ck_social_provider_state" CHECK ((
          ("user"."social_provider"."is_valid" = TRUE AND "user"."social_provider"."deleted_at" IS NULL)
          OR
          ("user"."social_provider"."is_valid" = FALSE AND "user"."social_provider"."deleted_at" IS NOT NULL)
          ))
);
--> statement-breakpoint
CREATE TABLE "user"."social_user" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "user"."social_user_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" bigint NOT NULL,
	"provider_id" bigint NOT NULL,
	"provider_user_name" varchar(255) NOT NULL,
	CONSTRAINT "pk_social_user" PRIMARY KEY("id"),
	CONSTRAINT "uq_social_user_provider" UNIQUE("user_id","provider_id","provider_user_name")
);
--> statement-breakpoint
CREATE TABLE "user"."user" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "user"."user_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_name" varchar(255) NOT NULL,
	"real_name" varchar(255),
	"phone_number" varchar(20),
	"email" varchar(255),
	"auth_type" "user"."auth_type" DEFAULT 'NATIVE' NOT NULL,
	"auth_role" "user"."auth_role" DEFAULT 'USER' NOT NULL,
	"created_at" timestamp (6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp (6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"deleted_at" timestamp (6) with time zone,
	CONSTRAINT "pk_user" PRIMARY KEY("id"),
	CONSTRAINT "ck_user_deleted_state" CHECK ((
          ("user"."user"."auth_role" <> 'LEFT' AND "user"."user"."deleted_at" IS NULL)
          OR
          ("user"."user"."auth_role" = 'LEFT' AND "user"."user"."deleted_at" IS NOT NULL)
          ))
);
--> statement-breakpoint
ALTER TABLE "order"."cart" ADD CONSTRAINT "fk_cart_product" FOREIGN KEY ("product_id") REFERENCES "product"."product"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "order"."cart" ADD CONSTRAINT "fk_cart_user" FOREIGN KEY ("user_id") REFERENCES "user"."user"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "order"."cart_option" ADD CONSTRAINT "fk_cart_detail_option" FOREIGN KEY ("id") REFERENCES "product"."detail_option"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "order"."cart_option" ADD CONSTRAINT "fk_cart_option" FOREIGN KEY ("cart_id") REFERENCES "order"."cart"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "order"."delivery" ADD CONSTRAINT "fk_delivery_payment" FOREIGN KEY ("id") REFERENCES "order"."payment"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "order"."order" ADD CONSTRAINT "fk_order_payment" FOREIGN KEY ("payment_id") REFERENCES "order"."payment"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "order"."order_option" ADD CONSTRAINT "fk_order_option" FOREIGN KEY ("order_id") REFERENCES "order"."order"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "order"."payment" ADD CONSTRAINT "fk_payment_method" FOREIGN KEY ("payment_method_id") REFERENCES "order"."payment_method"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "order"."payment" ADD CONSTRAINT "fk_payment_user" FOREIGN KEY ("user_id") REFERENCES "user"."user"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "product"."detail_option" ADD CONSTRAINT "fk_detail_option" FOREIGN KEY ("option_id") REFERENCES "product"."option"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "product"."option" ADD CONSTRAINT "fk_option_category" FOREIGN KEY ("major_category_id") REFERENCES "public"."major_category"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "product"."product" ADD CONSTRAINT "fk_product_category" FOREIGN KEY ("miner_category_id") REFERENCES "public"."miner_category"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "product"."product_image" ADD CONSTRAINT "fk_product_image" FOREIGN KEY ("id") REFERENCES "product"."product"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "miner_category" ADD CONSTRAINT "fk_category" FOREIGN KEY ("major_category_id") REFERENCES "public"."major_category"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "user"."address" ADD CONSTRAINT "fk_address_user" FOREIGN KEY ("user_id") REFERENCES "user"."user"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "user"."native_user" ADD CONSTRAINT "fk_native_user" FOREIGN KEY ("id") REFERENCES "user"."user"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "user"."refresh_token" ADD CONSTRAINT "fk_refresh_token_user" FOREIGN KEY ("user_id") REFERENCES "user"."user"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "user"."social_user" ADD CONSTRAINT "fk_social_user" FOREIGN KEY ("user_id") REFERENCES "user"."user"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "user"."social_user" ADD CONSTRAINT "fk_social_provider" FOREIGN KEY ("provider_id") REFERENCES "user"."social_provider"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
CREATE INDEX "ix_active_cart" ON "order"."cart" USING btree ("user_id","created_at","product_id");--> statement-breakpoint
CREATE INDEX "ix_cart_id" ON "order"."cart_option" USING btree ("cart_id");--> statement-breakpoint
CREATE INDEX "ix_order_payment" ON "order"."order" USING btree ("payment_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_order_option_sort" ON "order"."order_option" USING btree ("order_id","sort_key");--> statement-breakpoint
CREATE INDEX "ix_payment_method" ON "order"."payment" USING btree ("payment_method_id");--> statement-breakpoint
CREATE INDEX "ix_pending_payment_created_at" ON "order"."payment" USING btree ("created_at" DESC NULLS LAST) WHERE "order"."payment"."payment_status" = 'PENDING';--> statement-breakpoint
CREATE INDEX "ix_completed_payment_created_at" ON "order"."payment" USING btree ("created_at" DESC NULLS LAST) WHERE "order"."payment"."payment_status" = 'COMPLETED';--> statement-breakpoint
CREATE INDEX "ix_cancled_payment_deleted_at" ON "order"."payment" USING btree ("deleted_at" DESC NULLS LAST) WHERE "order"."payment"."payment_status" = 'CANCELED';--> statement-breakpoint
CREATE INDEX "ix_active_payment_method_created_at" ON "order"."payment_method" USING btree ("created_at" DESC NULLS LAST) WHERE "order"."payment_method"."is_valid" = TRUE;--> statement-breakpoint
CREATE INDEX "ix_delete_payment_method_deleted_at" ON "order"."payment_method" USING btree ("deleted_at" DESC NULLS LAST) WHERE "order"."payment_method"."is_valid" = FALSE;--> statement-breakpoint
CREATE UNIQUE INDEX "uq_detail_option_value" ON "product"."detail_option" USING btree ("option_id","option_value" DESC NULLS LAST) WHERE "product"."detail_option"."is_valid" = TRUE;--> statement-breakpoint
CREATE UNIQUE INDEX "uq_active_detail_option" ON "product"."detail_option" USING btree ("option_id","detail_option_name") WHERE "product"."detail_option"."is_valid" = TRUE;--> statement-breakpoint
CREATE UNIQUE INDEX "uq_active_option" ON "product"."option" USING btree ("major_category_id","option_name") WHERE "product"."option"."is_valid" = TRUE;--> statement-breakpoint
CREATE INDEX "ix_option_sort" ON "product"."option" USING btree ("major_category_id","sort_key") WHERE "product"."option"."is_valid" = TRUE;--> statement-breakpoint
CREATE INDEX "ix_active_product" ON "product"."product" USING btree ("is_recommended" DESC NULLS LAST,"miner_category_id","created_at" DESC NULLS LAST,"price") WHERE "product"."product"."is_valid" = TRUE;--> statement-breakpoint
CREATE UNIQUE INDEX "uq_active_major_category" ON "major_category" USING btree ("major_category_name") WHERE "major_category"."is_valid" = TRUE;--> statement-breakpoint
CREATE INDEX "ix_major_category_sort" ON "major_category" USING btree ("sort_key") WHERE "major_category"."is_valid" = TRUE;--> statement-breakpoint
CREATE UNIQUE INDEX "uq_active_miner_category" ON "miner_category" USING btree ("major_category_id","miner_category_name") WHERE "miner_category"."is_valid" = TRUE;--> statement-breakpoint
CREATE INDEX "ix_miner_category_sort" ON "miner_category" USING btree ("sort_key") WHERE "miner_category"."is_valid" = TRUE;--> statement-breakpoint
CREATE UNIQUE INDEX "uq_main_address" ON "user"."address" USING btree ("user_id") WHERE "user"."address"."is_main" = TRUE;--> statement-breakpoint
CREATE INDEX "ix_address_main" ON "user"."address" USING btree ("user_id","is_main" DESC NULLS LAST,"created_at") WHERE "user"."address"."is_valid" = TRUE;--> statement-breakpoint
CREATE INDEX "ix_refresh_token_user" ON "user"."refresh_token" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "ix_refresh_token_expire" ON "user"."refresh_token" USING btree ("expires_at");--> statement-breakpoint
CREATE INDEX "ix_active_social_provider_created_at" ON "user"."social_provider" USING btree ("created_at" DESC NULLS LAST) WHERE "user"."social_provider"."is_valid" = TRUE;--> statement-breakpoint
CREATE INDEX "ix_delete_social_provider_deleted_at" ON "user"."social_provider" USING btree ("deleted_at" DESC NULLS LAST) WHERE "user"."social_provider"."is_valid" = FALSE;--> statement-breakpoint
CREATE UNIQUE INDEX "uq_user_name" ON "user"."user" USING btree ("user_name") WHERE "user"."user"."auth_type" <> 'SOCIAL' AND "user"."user"."auth_role" <> 'LEFT';--> statement-breakpoint
CREATE INDEX "ix_active_user_created_at" ON "user"."user" USING btree ("created_at" DESC NULLS LAST) WHERE "user"."user"."auth_role" <> 'LEFT';--> statement-breakpoint
CREATE INDEX "ix_delete_user_deleted_at" ON "user"."user" USING btree ("deleted_at" DESC NULLS LAST) WHERE "user"."user"."auth_role" = 'LEFT';